name: LengLeng
options:
  bundleIdPrefix: com.lengleng
  deploymentTarget:
    iOS: 15.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
targets:
  LengLeng:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lengleng.app
    info:
      path: Sources/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        LSRequiresIPhoneOS: true
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
    resources:
      - path: Sources/GoogleService-Info.plist 